### ISSUE TITLE
VPN Killswitch

### ISSUE THREAD

**Issue by Skylead** [nstinus/nordvpn#14]
Feature I miss with the nordvpn client vs the PIA was their implementation of a killswitch in their client https://www.privateinternetaccess.com/forum/discussion/22605/vpn-killswitch

Would be great for udp connections especially

**Comment by pmo** [comment]
should be easy with "killall" :-D

**Comment by nstinus** [comment]
The nordvpn script relies on an external dependency to update resolv.conf. By default,
 it will install [openvpn-update-resolv-conf](https://github.com/masterkorp/openvpn-update-resolv-conf); but alternatively, if the package [vpnfailsafe](https://github.com/wknapik/vpnfailsafe) is installed, it will use it instead. I admit it is not properly documented but would you like to try this?

**Comment by Skylead** [comment]
I can do some testing this weekend and get back to you

**Comment by Skylead** [comment]
I can confirm that with vpnfailsafe installed the killswitch was active.Should `nordvpn stop` remove the killswitch? I was still in a killswitch state until system restart

**Comment by sanyikaz** [comment]
If i remember correctly i had to restore settings using 
iptables-restore < /etc/iptables/simple_firewall.rules

Now, on vpnfailsafe page it shows: 

> vpnfailsafe will revert all changes when the tunnel is closed, except for the firewall rules. You can restore those using the init script that set the iptables rules on boot, or by otherwise removing the VPNFAILSAFE_INPUT, VPNFAILSAFE_OUTPUT and VPNFAILSAFE_FORWARD chains.

Also, the entries in /etc/hosts for the VPN servers might get stale and require removal.

**Comment by nstinus** [comment]
@Skylead: it is a fair question and honestly I don't know. As @sanyikaz is pointing out, it is expected behavior.
At this stage, either we see if vpnfailsafe has a mode a bit more accommodating to your needs or we implement it here. To be honest I don't know much about that kind of tech and I'd rather rely on something that appears a bit more reliable.

I have created a ticket https://github.com/wknapik/vpnfailsafe/issues/16. Feel free to weigh in.

**Comment by Skylead** [comment]
Looks like the owner got to the post before I did, thanks for following up

**Comment by nstinus** [comment]
Recent addition to vpnfailsafe behaves as described here. I suggest we keep it as it was before and add another command to reset the firewall rules as to not leak by mistake.
I am working on a configuration file where you could amend that as you wish.

**Comment by Skylead** [comment]
sounds good
