### ISSUE TITLE
Line 19, float instead of int ?

### ISSUE THREAD

**Issue by AxVE** [nstinus/nordvpn#17]
In the nordvpn file, line 19.
The printf get an error, for example (sorry, it's in french) : 
```
#########################################################################    0,0%/usr/bin/nordvpn: ligne 19 : printf: 99.86313868613138686100: nombre non valable
#########################################################################    0,0%/usr/bin/nordvpn: ligne 19 : printf: 99.90875912408759124000: nombre non valable
#########################################################################    0,0%/usr/bin/nordvpn: ligne 19 : printf: 99.95437956204379562000: nombre non valable
```
_nombre non valable_ means invalid number.

**Comment by nstinus** [comment]
Hi, I just pushed a change that removes the progress bars altogether. It actually makes the update a bit faster.

**Comment by AxVE** [comment]
Hi,
thanks for this. I don't really know what can be particular in my machine so I get this error.
Anyway, it works and it's faster ! :D
