### ISSUE TITLE
rank returns ping pipe 4 in results list

### ISSUE THREAD

**Issue by phi1-h** [nstinus/nordvpn#20]
i think pipe 4 means, there was no return package and therefore the output shouldnt be submitted, right?

**Comment by nstinus** [comment]
Could you please paste here your command and the console output, possibly running your command with the -v option?

**Comment by phi1-h** [comment]
I cannot repeat the issue. It was something like:
de110 pipe 4
de111 pipe 4
Until de120
These were shown as the servers with the fastest ping

**Comment by nstinus** [comment]
Confirmed. Seems to happen when ping can't hit the server and returns an error.

**Comment by phi1-h** [comment]
Should be easy to resolve with error output to &> /dev/null or checking whether the last command exit wasn't 0 right? 😉
