### ISSUE TITLE
Failed to stop \xe2\x97\x8f.service: Unit \xe2\x97\x8f.service not loaded.

### ISSUE THREAD

**Issue by madddmike** [nstinus/nordvpn#21]
When I try to run  nordvpn start us813 as root I get the following:

Failed to stop \xe2\x97\x8f.service: Unit \xe2\x97\x8f.service not loaded.

What does that mean?

**Comment by nstinus** [comment]
That is most likely due to a previous 'start' on a bad server. That causes a failed service to linger and the script tries to stop it. Could you try with the -v option next time to confirm?

**Comment by nstinus** [comment]
No answer in two weeks. I am assuming it is fine. Feel free to comment if needed.

**Comment by ronnyrockel** [comment]
hello
I have the same issue as madddmike 

`sudo nordvpn -v status
+ shift
+ '[' 1 -ne 0 ']'
+ case "$1" in
+ command=status
+ shift
+ break
+ '[' -z status ']'
++ id -u
+ '[' 0 -ne 0 ']'
++ find /etc/openvpn/client -type f -name '*.nordvpn.com.*.ovpn'
++ wc -l
+ declare -r -i files_present=2437
++ find /etc/openvpn/client/nordvpn -type f -name etag -mmin -2880
++ wc -l
+ declare -r -i up_to_date=1
+ '[' 2437 -eq 0 ']'
+ '[' status '!=' status ']'
+ case $command in
++ get_service
++ systemctl --type=service
++ grep openvpn-client@nordvpn
++ awk '{print $1}'
+ service=●
+ test -z ●
+ systemctl status ●
Unit \xe2\x97\x8f.service could not be found.
`

how do I solve this?
