### ISSUE TITLE
some service is missing?

### ISSUE THREAD

**Issue by JAicewizard** [nstinus/nordvpn#34]
#when I try to run it using nordvpn start {server name} sometimes give back "Failed to stop \xe2\x97\x8f.service: Unit \xe2\x97\x8f.service not loaded." and sometimes not.
when I run the status command it alwasy gives back "Unit \xe2\x97\x8f.service could not be found."
when I havnt filled in the credentials the start/stop runs fine and so does the status, it just doesnt actually connect.

**Comment by JAicewizard** [comment]
turned out to be a problem with openvpn, not this script.

**Comment by wbecker** [comment]
i have this problem too, what was the solution @JAicewizard ?

**Comment by JAicewizard** [comment]
Honestly, Idk. 
Tried reinstalling nordvpn &  openvpn?
Also try completely purging openvpn and all its config files.
I think I just reinstalled arch or something along the lines of.
Also try rebooting a bunch of times, it's basically all I can remember of that night, or any other troubleshooting night (sleep drunk I guess).

**Comment by wbecker** [comment]
Yeah got it working. I think the problem was I had to upgrade a bunch of arch packages before I installed this. Rebooting seems to have fixed it

**Comment by JAicewizard** [comment]
see? its always the rebooting that fixes life.
wish I could to that in real life.
