### ISSUE TITLE
Unable to install on Arch Linux (commit problem)

### ISSUE THREAD

**Issue by mhammill** [nstinus/nordvpn#39]
Unable to build today 21 October 2018 23:20 CET.  Got:
`
$  Yaourt -S openvpn-nordvpn
[master c069a8f] saving uncommitted changes in /etc prior to pacman run
 Author: mike <mike@polly.lan.kattugglan.net>
 1 file changed, 3 insertions(+)

==> Downloading openvpn-nordvpn PKGBUILD from AUR...
x .SRCINFO
x PKGBUILD
x openvpn-nordvpn.install
redman commented on 2017-10-23 05:49			 
Since a week I use this tool, so I now first have to thank you!

I now tried to update in Pamac but helas ...
Thanks in advance for your ongoing efforts!

#
Synchronizing package databases...
Starting full system upgrade...

Preparing...

Building openvpn-nordvpn...
Cloning into 'openvpn-nordvpn'...
remote: Counting objects: 276, done.        
remote: Compressing objects: 100% (231/231), done.        
remote: Total 276 (delta 134), reused 104 (delta 45)        
Receiving objects: 100% (276/276), 38.90 KiB | 2.43 MiB/s, done.
Resolving deltas: 100% (134/134), done.
== Making package: openvpn-nordvpn 0.1.32-1 (Mon 23 Oct 07:37:18 CEST 2017)
== Checking runtime dependencies...
== Checking buildtime dependencies...
== Retrieving sources...
- Cloning nordvpn git repo...
Cloning into bare repository '/tmp/pamac-build-afw/openvpn-nordvpn/nordvpn'...
remote: Counting objects: 358, done.        
remote: Compressing objects: 100% (52/52), done.        
remote: Total 358 (delta 62), reused 118 (delta 59), pack-reused 235        
Receiving objects: 100% (358/358), 62.30 KiB | 701.00 KiB/s, done.
Resolving deltas: 100% (177/177), done.
== Validating source files with sha1sums...
nordvpn ... Skipped
== Extracting sources...
- Creating working copy of nordvpn git repo...
Cloning into 'nordvpn'...
done.
fatal: 'v0.1-32-g595937f' is not a commit and a branch 'makepkg' cannot be created from it
== ERROR: Failure while creating working copy of nordvpn git repo
Aborting...
 `

**Comment by mhammill** [comment]
PS  I was able to install it.  Not really sure why the git error. Maybe you want to take a look.  Maybe it's Yaourt related.

**Comment by nstinus** [comment]
It was an issue on the way I distributed the package.
