### ISSUE TITLE
Running connection through TCP instead of UDP

### ISSUE THREAD

**Issue by wtzb** [nstinus/nordvpn#6]
Is there a way for me to let the connection go through TCP, instead of UDP?

**Comment by nstinus** [comment]
A quick (and dirty) way for you would be to `sed 's/udp1194/tcp443/g' nordvpn -i`.

I am guessing people would probably always rather have all their connections through either udp or tcp. As such, I'll add an option in a configuration file (#3).
If you think you'd want to change it more often, I can also add a flag like `nordvpn start [-t|--tcp]`. Let me know what you prefer.

**Comment by nstinus** [comment]
Please try the `next` branch. `start` now has a `-t`, `--tcp` option.
If you use the ArchLinux package, this should do the trick:
```
 diff --git a/PKGBUILD b/PKGBUILD
index b48461a..3c52551 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -18,7 +18,7 @@ optdepends=('iputils: run ping and rank functions'
             'vpnfailsafe-git: use instead of update-resolv-conf if available')
 makedepends=('coreutils' 'pandoc')
 provides=('nordvpn')
-source=('git+https://github.com/nstinus/nordvpn.git#branch=master')
+source=('git+https://github.com/nstinus/nordvpn.git#branch=next')
 sha1sums=('SKIP')
 install=${pkgname}.install
```

**Comment by wtzb** [comment]
Thank you so much. I am indeed using the ArchLinux package, will try it out soon. Really appreciate the efforts you put into this!
