### ISSUE TITLE
Pick random vpn server

### ISSUE THREAD

**Issue by pmo** [nstinus/nordvpn#9]
Would be nice with a command to connect to a random server.

Example: "nordvpn -r" for truly random server, and "nordvpn -r us" for a random server in the US. ofc you could add --random too :-)

**Comment by nstinus** [comment]
I feel like pure random is of little use. You'd probably want to connect by default to a small set of servers; perhaps according to some feature (the closest, or less loaded, by country, netflix...). This information is now present thanks to #4. For this reason, I opened #11.
Let me know what you think.

**Comment by pmo** [comment]
What you explain sure has great uses too, that it connects to a "random" server close to you etc.. But trust me sometimes people would like random IP just like with tor browser :) if you have a small set of servers you use, combined with the browser you use, it makes it really easy to identify you, and kinda defeats the purpose of a VPN in some cases. I would personally use a less loaded function a lot in some cases :-)

**Comment by nstinus** [comment]
Sounds reasonable. Would you care to do the change and submit a merge request?

**Comment by pmo** [comment]
I will have a look at it :-)

**Comment by nstinus** [comment]
An alternative could be to introduce a new command: "pick". By default it would do what you suggest; then, leveraging the information we get in the infos command, it could do much more. Like picking a Netflix server for example or one that has a low load...

**Comment by Jhony33** [comment]
Any update for this feature?

**Comment by nstinus** [comment]
I just pushed a change to the command start.
If the server is not specified, it will randomly pick one from a [list of 5](https://nordvpn.com/servers/#recommended).
Note that this requires a working internet connection and for the jq program to be available in the PATH.
Thank you for your patience.

**Comment by Jhony33** [comment]
Thank you very much. :D
